from .types.typeddict import IndentMap as IndentMap
from typing import Iterator, NoReturn

formats: dict[str, str]

class EOFCommentsError(Exception): ...

class Comments:
    formats: dict[str, str]
    langs: dict[str, IndentMap]
    def __init__(self, mappings: dict[str, IndentMap] = ...) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def is_available(self, lang: str) -> bool: ...
    def fill_langs(self) -> NoReturn: ...
    def generate(self) -> dict[str, str]: ...
# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
