from typing import NoReturn

def error(*msg, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
def die(*msg, code: int = 0, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
