from collections import OrderedDict
from typing import NoReturn

formats: dict[str, str]

class EOFCommentsError(Exception): ...

class Comments:
    formats: OrderedDict[str, str]
    langs: OrderedDict[str, tuple[int, bool]]
    def __init__(self, **kwargs: dict[str, tuple[int, bool | None]]) -> None: ...
    def is_available(self, lang: str) -> bool: ...
    def fill_langs(self) -> NoReturn: ...
    def generate(self) -> dict[str, str]: ...
