from argparse import ArgumentParser
from typing import NoReturn

class ColorArgParser(ArgumentParser):
    colors: dict[str, str]
    def print_usage(self, file=None) -> None: ...
    def print_help(self, file=None) -> None: ...
    def exit(self, status: int = 0, message: str | None = None) -> NoReturn: ...
    def error(self, message: str) -> NoReturn: ...
